const products = [
    {
        name: 'Muichirou Tokito',
        image: '/images/kimetsu_muichiro.jpg',
        description: 'Muichirou Tokito Chibi figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 89.99,
        countInStock: 12,
        rating: 2,
        numReviews: 0,
    },
    {
        name: 'Sanemi Shinazugawa',
        image: '/images/kimetsu_sanemi.jpg',
        description: 'Sanemi Shinazugawa Chibi figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 89.99,
        countInStock: 12,
        rating: 3,
        numReviews: 0,
    },
    {
        name: 'Giyu Tomioka',
        image: '/images/kimetsu_giyuu.jpg',
        description: 'Giyu Tomioka Chibi figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 89.99,
        countInStock: 12,
        rating: 2,
        numReviews: 0,
    },
    {
        name: 'Kamado Tanjiro',
        image: '/images/kimetsu_tanjiro.jpg',
        description: 'Kamado Tanjiro Chibi figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 89.99,
        countInStock: 12,
        rating: 1,
        numReviews: 0,
    },
    {
        name: 'Akaza vs Rengoku',
        image: '/images/akaza_vs_rengoku.jpg',
        description: 'Akaza vs Rengoku Battle figurine',
        brand: 'AVPrto',
        category: 'Kimetsu',
        price : 199.99,
        countInStock: 12,
        rating: 5,
        numReviews: 0,
    },
    {
        name: 'Kokushibou',
        image: '/images/kimetsu_kokushibou.jpg',
        description: 'Kokushibou Chibi figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 149.99,
        countInStock: 12,
        rating: 5,
        numReviews: 0,
    },
    {
        name: 'Tanjiro vs Rui',
        image: '/images/tanjiro_vs_rui.jpg',
        description: 'Tanjiro vs Rui Battle figurine',
        brand: 'Banpresto',
        category: 'Kimetsu',
        price : 189.99,
        countInStock: 12,
        rating: 5,
        numReviews: 0,
    },
]

export default products